namespace WindowsAutomationPlugin.Models.Enums
{
    public enum ElementType
    {
        Button,
        Calendar,
        CheckBox,
        ComboBox,
        DataGridView,
        DateTimePicker,
        Grid,
        GridCell,
        GridHeader,
        GridHeaderItem,
        GridRow,
        HorizontalScrollBar,
        Label,
        ListBox,
        ListBoxItem,
        Menu,
        MenuItem,
        ProgressBar,
        RadioButton,
        Slider,
        Spinner,
        Tab,
        TabItem,
        TextBox,
        Thumb,
        TitleBar,
        ToggleButton,
        Tree,
        TreeItem,
        Type,
        VerticalScrollBar,
        Window
    }
}
